### ISSUE TITLE
Error messages given to user

### ISSUE THREAD

**Issue by Ivo-Evans** [fac19/week8-TheElite4#32]
We were really impressed by how cleanly your project hung together, and thought this was an area for improvement. Here are ideas from the team:

- The only error message we saw is ```something went wrong :(```. Maybe it would be more useful to a user to get more specific error messages
- The error messages on the page can stack - one way to fix this would be to clear the content of the #message div before rewriting it
- there's quite a lot of lag between doing something wrong and seeing an error message. I'm not sure how, but maybe this could somehow be optimised ??

**Comment by Joepock123** [comment]
Thanks Ivo!
